import argparse
import sys
import shutil
import json
import os
from pathlib import Path

# Try to find default skill file location relative to package
PACKAGE_ROOT = Path(__file__).parent.parent
DEFAULT_SKILL_PATH = PACKAGE_ROOT / "skills" / "devhive_workflow.md"

def get_default_skill_content():
    """Reads the devhive_workflow.md content from the package source."""
    if DEFAULT_SKILL_PATH.exists():
        return DEFAULT_SKILL_PATH.read_text()
    
    # Fallback content if file is missing
    return """# DevHive Workflow Orchestrator

This skill defines the autonomous execution loop for the DevHive AI software development pipeline.

## Core Rules
1. **Autonomous Execution**: Run the entire DevHive pipeline autonomously. Do not stop to ask the user for permission between each agent step unless an unrecoverable error occurs or the Explorer agent explicitly asks a `clarification_question`.
2. **Subagent Delegation**: You MUST use the `Task` tool with `subagent_type="general"` to execute the prompts generated by the MCP server. Do not execute the prompts yourself in the main context.
3. **Strict JSON**: The DevHive MCP server expects strict JSON. Instruct the subagent to output ONLY valid JSON without markdown formatting.

## The Execution Loop

When a user asks you to build a feature or start a project using DevHive, follow this exact procedure:

### 1. Initialization
Use the `devhive_start_pipeline` tool.
- `project_name`: A short snake_case identifier derived from the request.
- `requirements`: The user's full request.

The tool will return a JSON envelope containing `status`, `agent`, `system_prompt`, `user_prompt`, `expected_keys`, and `task_description`.

### 2. Main Loop
While `status` is `"pending"`:

**A. Launch Subagent**
Use the `Task` tool with `subagent_type="general"`.
- `description`: The `task_description` from the envelope.
- `prompt`: Combine the `system_prompt` and `user_prompt` from the envelope. Append this CRITICAL instruction: *"You must ONLY output valid JSON containing these exact keys: {expected_keys}. Do not include any other text, markdown formatting, or explanations."*

**B. Submit Result**
Once the subagent returns its JSON output, use the `devhive_submit_result` tool.
- `project_name`: The current project name.
- `agent_name`: The `agent` from the current envelope.
- `llm_response`: The raw JSON output from the subagent.

**C. Process Server Response**
The tool will return a new envelope:
- If `status` == `"success"`: Print a brief update to the user. If `next_task` is present, update your envelope and repeat the loop.
- If `status` == `"error"`: The envelope has an error message. Launch the subagent again, provide the error and the previous output, and ask it to fix the JSON structure. Retry up to 3 times.
- If `status` == `"complete"`: The pipeline is finished. Give the user a final summary and exit the loop.
"""

def configure():
    print("DevHive CLI Configuration")
    print("-------------------------")

    # 1. Ask user for client type
    while True:
        choice = input("Do you use OpenCode, Copilot, or both? [opencode/copilot/both]: ").lower().strip()
        if choice in ["opencode", "copilot", "both"]:
            break
        print("Invalid choice. Please type 'opencode', 'copilot', or 'both'.")

    # 2. Locate source file
    cwd_skill = Path("skills/devhive_workflow.md").resolve()
    pkg_skill = DEFAULT_SKILL_PATH.resolve()
    
    source_to_use = None
    
    if cwd_skill.exists():
        print(f"[+] Found skill file in current directory: {cwd_skill}")
        source_to_use = cwd_skill
    elif pkg_skill.exists():
        print(f"[+] Found skill file in package: {pkg_skill}")
        source_to_use = pkg_skill
    else:
        print("[-] skills/devhive_workflow.md not found.")
        print("[*] Using embedded default skill prompt.")
        temp_path = Path("devhive_workflow.md").resolve()
        try:
            with open(temp_path, "w") as f:
                f.write(get_default_skill_content())
            print(f"[+] Created temporary source file at: {temp_path}")
            source_to_use = temp_path
        except Exception as e:
            print(f"[-] Failed to create source file: {e}")
            return

    # 3. Configure OpenCode
    if choice in ["opencode", "both"]:
        # Remove legacy agent
        old_agent_dir = Path.home() / ".config" / "opencode" / "agents"
        old_agent = old_agent_dir / "DevHive0119.md"
        if old_agent.exists():
            print(f"[*] Removing legacy OpenCode agent: {old_agent}")
            try:
                old_agent.unlink()
            except Exception as e:
                print(f"[-] Could not remove legacy agent: {e}")
        
        dest_dir = Path.home() / ".config" / "opencode" / "skills"
        dest_file = dest_dir / "devhive_workflow.md"
        _copy_agent_file(source_to_use, dest_dir, dest_file, "OpenCode Skill")
        _configure_devhive()

    # 4. Configure Copilot
    if choice in ["copilot", "both"]:
        # Remove legacy agent
        old_agent_dir = Path.home() / ".copilot" / "agents"
        old_agent = old_agent_dir / "DevHive.md"
        if old_agent.exists():
            print(f"[*] Removing legacy Copilot agent: {old_agent}")
            try:
                old_agent.unlink()
            except Exception as e:
                print(f"[-] Could not remove legacy agent: {e}")

        dest_dir = Path.home() / ".copilot" / "instructions"
        dest_file = dest_dir / "devhive_workflow.md"
        _copy_agent_file(source_to_use, dest_dir, dest_file, "Copilot Instructions")
        _configure_vscode_copilot(dest_file)

    print("\nConfiguration complete!")

def _copy_agent_file(source, dest_dir, dest_file, client_name):
    print(f"\n--- Configuring {client_name} ---")
    try:
        if not dest_dir.exists():
            print(f"[*] Creating directory: {dest_dir}")
            dest_dir.mkdir(parents=True, exist_ok=True)
        
        shutil.copy2(source, dest_file)
        print(f"[+] Successfully installed agent to: {dest_file}")
    except Exception as e:
        print(f"[-] Failed to configure {client_name}: {e}")

def _configure_vscode_copilot(agent_file_path):
    print("\n--- Configuring VS Code Copilot ---")
    confirm = input("Do you want to add DevHive instructions to VS Code global settings? [y/N]: ").lower().strip()
    if confirm != 'y':
        return

    # Standard VS Code settings path on Linux/Mac
    settings_path = Path.home() / ".config" / "Code" / "User" / "settings.json"
    
    if not settings_path.exists():
        # Try macOS path if Linux path fails
        settings_path_mac = Path.home() / "Library" / "Application Support" / "Code" / "User" / "settings.json"
        if settings_path_mac.exists():
            settings_path = settings_path_mac
        else:
            print(f"[-] VS Code settings not found at standard locations.")
            return

    try:
        with open(settings_path, "r") as f:
            # Handle comments in json if present (VS Code allows comments, generic json parser doesn't)
            # Simple approach: try standard load, fail if comments
            try:
                config = json.load(f)
            except json.JSONDecodeError:
                print("[-] Failed to parse settings.json (might contain comments). Skipping automatic update.")
                print(f"[*] Please manually add 'github.copilot.chat.codeGeneration.instructions' pointing to: {agent_file_path}")
                return

        key = "github.copilot.chat.codeGeneration.instructions"
        
        # Prepare instruction object
        instruction_entry = {"file": str(agent_file_path)}
        
        if key not in config:
            config[key] = [instruction_entry]
        else:
            # If it's a list, append if not exists
            if isinstance(config[key], list):
                # Check for duplicates
                exists = False
                for item in config[key]:
                    if isinstance(item, dict) and item.get("file") == str(agent_file_path):
                        exists = True
                        break
                if not exists:
                    config[key].append(instruction_entry)
            else:
                # If it's weird (legacy string?), convert to list
                print(f"[*] converting existing '{key}' to list format")
                config[key] = [instruction_entry]

        # Backup first
        shutil.copy2(settings_path, str(settings_path) + ".bak")
        print(f"[*] Backed up settings to: {str(settings_path)}.bak")

        with open(settings_path, "w") as f:
            json.dump(config, f, indent=4)
            
        print(f"[+] Updated VS Code settings at: {settings_path}")
        
    except Exception as e:
        print(f"[-] Failed to update VS Code settings: {e}")

def _configure_devhive():
    print("\n--- Configuring MCP Server Connection ---")
    confirm = input("Do you want to add the DevHive MCP server to OpenCode config? [y/N]: ").lower().strip()
    if confirm != 'y':
        return

    # Default locations to check
    possible_paths = [
        Path.home() / ".config" / "opencode" / "opencode.json",
        Path.home() / ".config" / "opencode" / "config.json"
    ]
    
    default_config = possible_paths[0]
    for p in possible_paths:
        if p.exists():
            default_config = p
            break

    config_path_str = input(f"Enter path to OpenCode config [{default_config}]: ").strip()
    
    if not config_path_str:
        config_path = default_config
    else:
        config_path = Path(config_path_str).expanduser().resolve()

    if not config_path.exists():
        print(f"[-] Config file not found at: {config_path}")
        create = input("Create new config file? [y/N]: ").lower().strip()
        if create == 'y':
            try:
                config_path.parent.mkdir(parents=True, exist_ok=True)
                with open(config_path, "w") as f:
                    json.dump({"mcp": {}}, f, indent=2)
                print(f"[+] Created new config file.")
            except Exception as e:
                print(f"[-] Failed to create config: {e}")
                return
        else:
            return

    try:
        with open(config_path, "r") as f:
            config = json.load(f)
        
        if "mcp" not in config:
            config["mcp"] = {}

        # Detect Python Interpreter
        python_cmd = sys.executable
        
        # Check for .venv in current directory
        venv_python = Path.cwd() / ".venv" / "bin" / "python"
        if venv_python.exists():
            print(f"[*] Found virtual environment at: {venv_python}")
            use_venv = input(f"Use this virtual environment for the server? [Y/n]: ").lower().strip()
            if use_venv in ['', 'y', 'yes']:
                python_cmd = str(venv_python)
        
        # Construct command
        server_command = [python_cmd, "-m", "devhive.server"]
        
        config["mcp"]["devhive"] = {
            "type": "local",
            "command": server_command,
            "enabled": True
        }
        
        with open(config_path, "w") as f:
            json.dump(config, f, indent=2)
            
        print(f"[+] Updated MCP config at: {config_path}")
        print(f"    Server command: {' '.join(server_command)}")
        
    except Exception as e:
        print(f"[-] Failed to update MCP config: {e}")

def start():
    """Starts the MCP server."""
    try:
        from devhive.server import main as server_main
        print(f"[*] Starting DevHive MCP Server (PID {os.getpid()})...")
        server_main()
    except ImportError:
        import traceback
        print("[-] DETALLE DEL ERROR REAL:")
        traceback.print_exc() # <-- MOSTRAR QUÉ FALLÓ, LÍNEA POR LÍNEA

        # Check for venv and restart
        venv_python = Path.cwd() / ".venv" / "bin" / "python"
        if venv_python.exists() and sys.executable != str(venv_python):
            print(f"[*] 'mcp' not found in current environment.")
            print(f"[*] Switching to virtual environment at: {venv_python}")
            # Re-execute using venv python
            os.execv(str(venv_python), [str(venv_python)] + sys.argv)
        else:
            print("[-] Error: Could not import devhive.server")
            print("[-] Ensure dependencies are installed or activate your virtual environment.")
            return
    except KeyboardInterrupt:
        print("\n[!] Server stopped by user.")
    except Exception as e:
        print(f"[-] Server error: {e}")

def main():
    parser = argparse.ArgumentParser(description="DevHive CLI")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Configure command
    configure_parser = subparsers.add_parser("configure", help="Configure DevHive agent for OpenCode/Copilot")
    
    # Start command
    start_parser = subparsers.add_parser("start", help="Start the MCP server locally")

    # If no arguments, print help
    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    args = parser.parse_args()

    if args.command == "configure":
        configure()
    elif args.command == "start":
        start()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
