from typing import Dict, Any
from mcp.server.fastmcp import FastMCP
from mcp_server.orchestrator.ceo import ceo_decision_logic
from mcp_server.schemas.project_models import ProjectState
from mcp_server.tools.explorer import explorer_analysis
from mcp_server.tools.proposal import product_proposal
from mcp_server.tools.architect import architecture_design
from mcp_server.tools.tasks import task_breakdown
from mcp_server.tools.implementation import implementation_plan
from mcp_server.tools.testing import testing_strategy
from mcp_server.tools.verification import verification_report
from mcp_server.tools.archive import archive_feature

mcp = FastMCP("DevHive Dynamic Organization")

@mcp.tool()
def create_new_project(feature_request: str) -> Dict[str, Any]:
    """
    Initializes a new project state with the given request.
    Use this to start the workflow.
    """
    state = ProjectState(feature_request=feature_request)
    return state.model_dump()

@mcp.tool()
def ceo_decision(project_state: Dict[str, Any]) -> Dict[str, Any]:
    """
    The CEO Agent reviews the project state and recommends the next role/tool to call.
    Always call this tool after a role tool completes to decide what to do next.
    """
    return ceo_decision_logic(project_state)

@mcp.tool()
def explorer_tool(project_state: Dict[str, Any], user_needs: list[str], constraints: list[str], dependencies: list[str], risks: list[str]) -> Dict[str, Any]:
    """
    Analyst Role: Records the requirements analysis.
    Arguments must be generated by the Agent based on the feature request.
    """
    return explorer_analysis(project_state, user_needs, constraints, dependencies, risks)

@mcp.tool()
def proposal_tool(project_state: Dict[str, Any], feature_description: str, user_value: str, acceptance_criteria: list[str], scope: str) -> Dict[str, Any]:
    """
    Product Manager Role: Records the product proposal.
    Arguments must be generated by the Agent based on the analysis.
    """
    return product_proposal(project_state, feature_description, user_value, acceptance_criteria, scope)

@mcp.tool()
def architect_tool(project_state: Dict[str, Any], architecture_pattern: str, components: list[str], data_models: list[dict], apis: list[str]) -> Dict[str, Any]:
    """
    Tech Lead Role: Records the architecture design.
    Arguments must be generated by the Agent based on the proposal.
    """
    return architecture_design(project_state, architecture_pattern, components, data_models, apis)

@mcp.tool()
def scrum_tool(project_state: Dict[str, Any], epics: list[str], tasks: list[dict], estimated_complexity: str) -> Dict[str, Any]:
    """
    Scrum Master Role: Records the task breakdown.
    Arguments must be generated by the Agent based on the architecture.
    """
    return task_breakdown(project_state, epics, tasks, estimated_complexity)

@mcp.tool()
def developer_tool(project_state: Dict[str, Any], implementation_strategy: str, file_structure: str, pseudocode: str) -> Dict[str, Any]:
    """
    Developer Role: Records the implementation plan.
    Arguments must be generated by the Agent based on the tasks.
    """
    return implementation_plan(project_state, implementation_strategy, file_structure, pseudocode)

@mcp.tool()
def qa_tool(project_state: Dict[str, Any], test_strategy: str, unit_tests: list[str], validation_plan: str) -> Dict[str, Any]:
    """
    QA Role: Records the testing strategy.
    Arguments must be generated by the Agent based on the implementation plan.
    """
    return testing_strategy(project_state, test_strategy, unit_tests, validation_plan)

@mcp.tool()
def auditor_tool(project_state: Dict[str, Any], architecture_consistency: bool, missing_pieces: list[str], security_risks: list[str]) -> Dict[str, Any]:
    """
    Auditor Role: Records the verification report.
    Arguments must be generated by the Agent after reviewing the whole project.
    """
    return verification_report(project_state, architecture_consistency, missing_pieces, security_risks)

@mcp.tool()
def archivist_tool(project_state: Dict[str, Any], project_summary: str) -> Dict[str, Any]:
    """
    Archivist Role: Archives the completed project.
    Arguments must be generated by the Agent.
    """
    return archive_feature(project_state, project_summary)

def main():
    mcp.run()

if __name__ == "__main__":
    main()
